apiVersion: v1
kind: Pod
metadata:
  name: mydemonodejs
  labels:
    app: mydemonodejslabel
spec:
  containers:
  - image: divine6/myapp:2.0
    name: myappcontainer
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: /app/ntemp
      name: demonodejsvolume
  volumes:
  - name: demonodejsvolume
    hostPath:
      path: /Users/divine/Documents/upskilling/minikubehostvolume
      type: Directory